collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5965953038539737
color:
  saturation: 0.1460403515957296
  brandStrength: 0.7142857
  lightness: 0.2435916687827557
  brandColors:
    - '#3B2F2F'
    - '#EAECDF'
    - '#C5C7B7'
    - '#9D776F'
    - '#0B0A0A'
  rhythmicContrast: 0.9268331746570766
layout_spectrum: 0.4987469
name: WinterWheat
navigation:
  - name: Webb & Co.
    id: a2bd5e4f-98f9-4a05-bf4f-58f79219cfdd
    type: content
